#!/bin/bash

PHYSICS_IMAGENAME="physics";

fail(){ echo "!!!! --> $1" && exit 1;  }

if [[ "$1" == "build" ]]; then
    docker build -t $PHYSICS_IMAGENAME .;
elif [[ "$1" == "run" ]]; then
    docker run -it -e DISPLAY=$DISPLAY -v /tmp.X11-unix:/tmp/.X11-unix:rw $PHYSICS_IMAGENAME;
else 
    fail "Unknown cli action requested '$1'";
fi;

